Streaming:
- Jellyfin:
    icon: jellyfin.png
    href: https://khalleessy.fr
    description: Les meilleurs Films au Meilleur Endroit.
    server: localhost
    container: Jellyfin
    widget:
      type: jellyfin
      url: https://khalleessy.fr
      key: 2995fa81029e44ea968e606fb7d546bb	
