---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

widget:
  type: jellyfin
  url: https://Khalleessy.fr
  key: 2995fa81029e44ea968e606fb7d546bb	
  enableBlocks: true # optional, defaults to false
  enableNowPlaying: true # optional, defaults to true
  enableUser: true # optional, defaults to false
  showEpisodeNumber: true # optional, defaults to false
  expandOneStreamToTwoRows: false # optional, defaults to true
